apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bluesky-pds.fullname" . }}-secret"
  labels:
    {{- include "bluesky-pds.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pdsJwtSecret }}
  jwt-secret: {{ .Values.pdsJwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}

  {{- if .Values.pdsPlcRotationKey }}
  plc-rotation-key: {{ .Values.pdsPlcRotationKey | b64enc | quote }}
  {{- else }}
  plc-rotation-key: {{ printf "%x" (randAlphaNum 32) | b64enc | quote }}
  {{- end }}

  {{- if not .Values.existingSecret }}
  {{- if .Values.pdsAdminPassword }}
  clouve-password: {{ .Values.pdsAdminPassword | b64enc | quote }}
  {{- else }}
  clouve-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
