---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canvas.fullname" . }}-env
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
data:
  REDIS_HOST: "{{ include "canvas.fullname" . }}-redis-master"
  POSTGRES_HOST: "{{ include "canvas.fullname" . }}-postgresql"
  POSTGRES_DB: "{{ .Values.postgresql.auth.database }}"
  POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
  ENCRYPTION_KEY: "{{ .Values.canvasEncryptionKey }}"
  RAILS_HOST_WITH_PORT: "{{ .Values.canvasHostname }}"
  CANVAS_LMS_ACCOUNT_NAME: "{{ .Values.canvasLmsAccountName }}"
  CANVAS_LMS_ADMIN_EMAIL: "{{ .Values.canvasLmsAdminEmail }}"
  CANVAS_LMS_STATS_COLLECTION: "opt_out"
  NGINX_MAX_UPLOAD_SIZE: "50M"
  RAILS_ENV: "production"
  UPDATE_ENCRYPTION_KEY_HASH: "1"
