kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "canvas.fullname" . }}-data"
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
