apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "canvas.fullname" . }}-secrets"
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  {{- if .Values.canvasLmsAdminPassword }}
  clouve-password: {{ .Values.canvasLmsAdminPassword | b64enc | quote }}
  {{- else }}
  clouve-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
