{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gibbon.fullname" . }}-secrets"
  labels:
    {{- include "gibbon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  clouve-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  clouve-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
